create database country;
use country;
create table country(id int,name varchar(20),countries int,states int,bird varchar(20),animal varchar(20));
select * from country;

alter table country add column pm_name varchar(20);
alter table country add column country_name varchar(20);
alter table country add column food varchar(20);
alter table country add column currency varchar(20);
alter table country add column population bigint;
alter table country add column language varchar(20);
alter table country add column time int;
alter table country add column day varchar(20);
alter table country add  column education varchar(30);
alter table country add column election varchar(20);
alter table country add column systems varchar(20);
alter table country add column states varchar(20);
alter table country add column district varchar(30);
alter table country add column militiry varchar(30);
alter table country add column capitals varchar(20);
alter table country add column no_of_language int;
alter table country add column mobile_code int;
alter table country add column culture varchar(20);
alter table country add column festivals varchar(20);
alter table country add column position int;

alter table country rename column pm_name to agriculture;
alter table country rename column country_name to education;
alter table country rename column food to sweet;
alter table country rename column currency to gst;
alter table country rename column population to generation;
alter table country rename column language to technology;
alter table country rename column time to timings;
alter table country rename column day to months;
alter table country rename  column education to culture;
alter table country rename column election to population;
alter table country rename column systems to pm_name;
alter table country rename column states to capitals;
alter table country rename column district to state;
alter table country rename column militiry to industries;
alter table country rename column capitals to manufacturing;
alter table country rename column no_of_language to no_of_companies;
alter table country rename column mobile_code to usd_code;
alter table country rename column culture to samskrit;
alter table country rename column festivals to famous_fest;

alter table country modify column  agriculture varchar(20);
alter table country modify column  education varchar(30);
alter table country modify column  sweet varchar(20);
alter table country modify column  gst int;
alter table country modify column  generation int;
alter table country modify column technology int;
alter table country modify column timings int;
alter table country modify column months varchar(20);
alter table country modify  column culture varchar(20);
alter table country modify column population bigint;
alter table country modify column pm_name varchar(40);
alter table country modify column capitals varchar(20);
alter table country modify column state varchar(30);
alter table country modify column  industries bigint;
alter table country modify column manufacturing varchar(30);
alter table country modify column no_of_companies bigint;
alter table country modify column usd_code int;
alter table country modify column samskrit varchar(20);
alter table country modify column famous_fest varchar(20);
